config = {
    'dataset': 'COVID-Q',
    'Augmentation_target_number': 70,
    'topk' : 3,
    "s2_lr_dc_step": 1,
    "s2_lr_dc": 0.99,
    "s2_learn_rate": 0.00001,
    "s2_train_epoch": 2,
    'recall_train_batch_size': 32,
    'classification_train_batch_size': 16,
    'test_batch_size': 8,
    'pretrain_batch_size': 8,
    'temperature': 0.1,
    "feat_cutoff_rate": 0.1,
    'max_seq_Q_len': 40,
    'max_seq_A_len': 40,
    "lr_dc_step": 2,
    "lr_dc": 0.1,
    "learn_rate": 0.0002,
    "train_epoch": 3,
    "pretrain_model": "sentence-transformers/all-MiniLM-L6-v2",
    "feature_dim":384,
    "bert-base-uncased": 768,
    "sentence-transformers/all-MiniLM-L6-v2": 384,
    "sentence-transformers/all-mpnet-base-v2": 768
}
